//@version=5
indicator(shorttitle="ETS BB", title="ETS Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
mult2 = input.float(3.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
dev2 = mult2 * ta.stdev(src, length)
upper = basis + dev
upper2 = basis + dev2
lower = basis - dev
lower2 = basis - dev2
offset = input.int(0, "Offset", minval = -500, maxval = 500)
plot(basis, "Basis", color=#b700ff, offset = offset)
p1 = plot(upper, "Upper", color=#29f8ff, offset = offset)
p2 = plot(lower, "Lower", color=#29f8ff, offset = offset)

p11 = plot(upper2, "Upper", color=#2ab6bb, offset = offset)
p22 = plot(lower2, "Lower", color=#2ab6bb, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))